drop view f_order_items_dataset;
drop view f_customers_dataset;
drop view f_geolocation_dataset;
drop view f_sellers_dataset;
drop view F_OD_OPD_ORD;
drop view F_PD_PC;
//edited for testing
create or replace view f_order_items_dataset as (select * from "HISTORICAL_LOAD"."GCP"."ORDER_ITEMS_DATASET"); 

create or replace view f_customers_dataset as (select * from "HISTORICAL_LOAD"."GCP"."CUSTOMERS_DATASET");

create or replace view f_geolocation_dataset as (select * from "HISTORICAL_LOAD"."GCP"."GEOLOCATION_DATASET");

create or replace view f_sellers_dataset as (select * from "HISTORICAL_LOAD"."GCP"."SELLERS_DATASET");

create or replace view F_OD_OPD_ORD as (select od.ORDER_ID,CUSTOMER_ID,ORDER_STATUS,ORDER_PURCHASE_TIMESTAMP,
  ORDER_APPROVED_AT,ORDER_DELIVERED_CARRIER_DATE,ORDER_DELIVERED_CUSTOMER_DATE,ORDER_ESTIMATED_DELIVERY_DATE,PAYMENT_SEQUENTIAL,PAYMENT_TYPE,
  PAYMENT_INSTALLMENTS,PAYMENT_VALUE,REVIEW_ID,REVIEW_SCORE,REVIEW_COMMENT_TITLE,REVIEW_COMMENT_MESSAGE,REVIEW_CREATION_DATE,REVIEW_ANSWER_TIMESTAMP 
  from "HISTORICAL_LOAD"."GCP"."ORDERS_DATASET" od join "HISTORICAL_LOAD"."GCP"."ORDER_PAYMENTS_DATASET" opd on od.ORDER_ID=opd.ORDER_ID 
  join "HISTORICAL_LOAD"."GCP"."ORDER_REVIEWS_DATASET" ord on od.ORDER_ID=ord.ORDER_ID); 
  
create or replace view F_PD_PC as (select PRODUCT_ID,pd.PRODUCT_CATEGORY_NAME,PRODUCT_CATEGORY_NAME_ENGLISH,
  PRODUCT_NAME_LENGHT,PRODUCT_DESCRIPTION_LENGHT,PRODUCT_PHOTOS_QTY,PRODUCT_WEIGHT_G,PRODUCT_LENGTH_CM,PRODUCT_HEIGHT_CM,PRODUCT_WIDTH_CM
  from "HISTORICAL_LOAD"."GCP"."PRODUCTS_DATASET" pd join "HISTORICAL_LOAD"."GCP"."PRODUCT_CATEGORY_NAME_TRANSLATION" pc on 
  pd.PRODUCT_CATEGORY_NAME=pc.PRODUCT_CATEGORY_NAME); 
