CREATE ROLE PROJECT_ANALYST;
CREATE ROLE PROJECT_ANALYST_REAL;
CREATE ROLE PROJECT_DEVELOPER;

-- grant warehouse access to roles
GRANT USAGE ON WAREHOUSE compute_wh TO ROLE PROJECT_ANALYST;
GRANT USAGE ON WAREHOUSE compute_wh TO ROLE PROJECT_ANALYST_REAL;
GRANT USAGE ON WAREHOUSE compute_wh TO ROLE PROJECT_DEVELOPER;

-- grant db access to roles
GRANT USAGE ON DATABASE PROJECT TO ROLE PROJECT_ANALYST;
GRANT USAGE ON DATABASE PROJECT TO ROLE PROJECT_ANALYST_REAL;
GRANT USAGE ON DATABASE PROJECT TO ROLE PROJECT_DEVELOPER;

-- grant schema access to roles
GRANT USAGE ON SCHEMA PROJECT1 TO ROLE PROJECT_ANALYST;
GRANT USAGE ON SCHEMA PROJECT1 TO ROLE PROJECT_ANALYST_REAL;
GRANT USAGE ON SCHEMA PROJECT1 TO ROLE PROJECT_DEVELOPER;

-- grant select privilege to analyst roles

GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_CUSTOMERS_DATASET" TO ROLE PROJECT_ANALYST;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_CUSTOMERS_DATASET" TO ROLE PROJECT_ANALYST_REAL;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_CUSTOMERS_DATASET" TO ROLE PROJECT_DEVELOPER;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_ORDER_ITEMS_DATASET" TO ROLE PROJECT_ANALYST;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_ORDER_ITEMS_DATASET" TO ROLE PROJECT_ANALYST_REAL;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_ORDER_ITEMS_DATASET" TO ROLE PROJECT_DEVELOPER;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_OD_OPD_ORD" TO ROLE PROJECT_ANALYST;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_OD_OPD_ORD" TO ROLE PROJECT_ANALYST_REAL;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_OD_OPD_ORD" TO ROLE PROJECT_DEVELOPER;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_GEOLOCATION_DATASET" TO ROLE PROJECT_ANALYST;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_GEOLOCATION_DATASET" TO ROLE PROJECT_ANALYST_REAL;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_GEOLOCATION_DATASET" TO ROLE PROJECT_DEVELOPER;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_PD_PC" TO ROLE PROJECT_ANALYST;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_PD_PC" TO ROLE PROJECT_ANALYST_REAL;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_PD_PC" TO ROLE PROJECT_DEVELOPER;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_SELLERS_DATASET" TO ROLE PROJECT_ANALYST;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_SELLERS_DATASET" TO ROLE PROJECT_ANALYST_REAL;
GRANT SELECT ON TABLE "PROJECT"."PROJECT1"."F_SELLERS_DATASET" TO ROLE PROJECT_DEVELOPER;
-- assign roles to a user
GRANT ROLE PROJECT_ANALYST TO USER shikha;
GRANT ROLE PROJECT_ANALYST_REAL TO USER shikha;
GRANT ROLE PROJECT_DEVELOPER TO USER shikha;

-- CREATE MASKING POLICY

create or replace masking policy sensitive_info_masking_numbers as (val int) returns int ->
  case
    when current_role() in ('PROJECT_ANALYST_REAL', 'ACCOUNTADMIN','SYSADMIN') then val
    else '0'
  end;
  
create or replace masking policy sensitive_info_masking_strings as (val STRING) returns STRING ->
  case
    when current_role() in ('PROJECT_ANALYST_REAL', 'PROJECT_DEVELOPER','SYSADMIN', 'ACCOUNTADMIN') then val
    else '*hidden*'
  end;
  
-- APPLY MASKING POLICY TO A TABLE's NUMBER COLUMN
ALTER VIEW  F_OD_OPD_ORD MODIFY COLUMN PAYMENT_VALUE SET MASKING POLICY sensitive_info_masking_numbers;

-- APPLY MASKING POLICY TO A TABLE's NUMBER COLUMN
ALTER VIEW F_ORDER_ITEMS_DATASET MODIFY COLUMN PRICE SET MASKING POLICY sensitive_info_masking_numbers;


-- APPLY THE MASKING POLICY TO A TABLE's STRING COLUMN
ALTER VIEW F_OD_OPD_ORD MODIFY COLUMN PAYMENT_TYPE SET MASKING POLICY sensitive_info_masking_strings;

-- SEE MASKING IN ACTION

USE ROLE PROJECT_ANALYST_REAL;
SELECT * FROM F_OD_OPD_ORD;
SELECT * FROM F_ORDER_ITEMS_DATASET;

USE ROLE PROJECT_ANALYST;
SELECT * FROM F_OD_OPD_ORD;
SELECT * FROM F_ORDER_ITEMS_DATASET;

USE ROLE PROJECT_DEVELOPER;
SELECT * FROM F_OD_OPD_ORD;
SELECT * FROM F_ORDER_ITEMS_DATASET;

DESC MASKING POLICY sensitive_info_masking_strings; 